### PR TITLE
New release 0.4.1: new features, bug fixes and package maintainer

### PR DESCRIPTION
**Pull request by rouben**
**Summary of changes**
- Fixed ZoL DKMS dependency in new debian (and derviative) OSs by @skrzepto.
- Added the ability to set the web server URL root in config by @timoid.
  - Fixed regression bug in @timoid's code with HTML templates not generating correct links relative to the configured web server URL root.
- Added myself as the package maintainer.

See change log for detailed descriptions of each included commit.

### CODE REVIEW

**Comment by skrzepto** [comment]
Might be better to maintain a new fork since the author seems to be unresponsive. Thoughts?

**Comment by timoid** [comment]
I ended up making the wwwroot patch due to original author being unresponsive.

**Comment by rouben** [comment]
Agree. I’ll close this PR.

**Comment by skrzepto** [comment]
@rouben whats the location of the new repo?

**Comment by rouben** [comment]
@skrzepto it's my fork at https://github.com/rouben/zfswatcher. AFAIK it's the most up to date, as I am using it to gather updates to the original codebase.

**Comment by snabb** [comment]
Hi @rouben and others,

I seriously recommend going ahead with the fork. I am the original author of this software, but I am unable to put any effort on it. It is soon 4 years since my last commit.

I am happy that people have apparently found it useful.

If there is anything that I could do to ease the transition, please tell me. It would have to be something that requires just a minimal effort. Maybe a link to the new repository at the top of the README file?

**Comment by rouben** [comment]
Hi @snabb,

Good to hear from you. I was on vacation and offline until now, and happy to see that you responded and noticed the efforts here. Thank you for the encouragement.

I suppose a link from your README to the new repo would be nice, thank you for offering! At some point I also want to revamp the website for zfswatcher; update it, link to the new repo, etc, and I'll probably just host it here on Github. When that happens I may also ask you to put in a similar link or redirect to the new site, from the existing site, when the new site is ready.

In the meantime, may I have your permission to copy the content, HTML and related assets from the [existing site](http://zfswatcher.damicon.fi/) for the new site?

Thanks!

**Comment by snabb** [comment]
Hi @rouben,

I have now added a link to your fork at the README (commit 50e5382719068d6dc20b256f0021183560697ea7).

The web site contents are also licensed under GPL. Thus you are free to use the content/HTML/assets under those terms.

Sorry about being a bit slow to reply! :)

**Pull request closed without merging**
